[package]
name = "cmark-spec"
description = "test pulldown-cmark with cmark spec test cases json"
version = "0.1.0"
authors = ["rnitta <attinyes@gmail.com>"]
edition = "2018"

[dependencies]
pulldown-cmark = "0.5.2"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
